// Central source of truth for NIVO AIMemory capacity parameters (M4.6 Issue 1)
export const AIMEMORY_LIMITS = {
  CREATOR_SUMMARY_MAX_LENGTH: 500,
  TOPICS_MAX_COUNT: 20,
  TOPIC_MAX_LENGTH: 100,
  HOOKS_MAX_COUNT: 15,
  HOOK_MAX_LENGTH: 200,
  SCRIPT_SUMMARIES_MAX_COUNT: 10,
  SCRIPT_SUMMARY_MAX_LENGTH: 250,
  PILLARS_MAX_COUNT: 5,
  PILLAR_MAX_LENGTH: 50,
};
